### PR TITLE
Optimize the icon for 16×16 px

### PR DESCRIPTION
**Pull request by enzet**
Hey, great icon!

I’ve tried to optimize the icon for the 16×16 px size by simplifying the vector image. It’s not polished enough, I just want you to see the idea.

### Comparison

To achieve pixel matching on Retina displays, the image should be downscaled by 50%.

Screenshot 2023-03-18 at 14 48 06

### CODE REVIEW

**Comment by enzet** [comment]
Fixed gradients:

Screenshot 2023-03-19 at 00 30 55

**Comment by SavchenkoValeriy** [comment]
Hi there, good to see you here :)
Looks great thanks! Can you also incorporate it into the `icns` file as well?

**Comment by enzet** [comment]
Is this the right way to do that?

```shell
mkdir Emacs.iconset
for scale in 16 32 48 64 128 256 512 1024
do
    cp Emacs@${scale}.png Emacs.iconset/icon_${scale}x${scale}.png
done
iconutil -c icns Emacs.iconset
rm -r Emacs.iconset
```

**Comment by enzet** [comment]
I'm afraid I did it wrong:

```diff
 Emacs.icns | Bin 827717 -> 254625 bytes
```

**Comment by SavchenkoValeriy** [comment]
> Is this the right way to do that?

I'm afraid I have no idea 😅 I used a Figma plugin to generate it in the first place, but it looks alright IMO.

**Pull request merged**
